version: "3"

services:
  postgres:
    image: postgres:14.2
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=bundlr
      - POSTGRES_PASSWORD=bundlr
      - POSTGRES_DATABASE=bundlr
  app:
    build: .
    ports:
      - "127.0.0.1:42069:42069"
    env_file:
      - .env
    volumes:
      - ./wallet.json:/wallet.json
      - /bundles:/bundles
    depends_on:
      - postgres