version: "3"

services:
  db:
    image: postgres:14.2
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=bundlr
      - POSTGRES_PASSWORD=bundlr
      - POSTGRES_DATABASE=bundlr
