[package]
name = "validator-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.15"
redis = { version = "0.21.4", features = ["tokio-comp"] }
serde = "1.0.132"
serde_json = "1.0.73"
tokio = "1.15.0"
bytes = "1.1.0"
derive_more = "0.99.17"
paris = { version = "1.5.8", features = ["timestamps", "macros"] }
data-encoding = { version = "2.3.2"
dotenv = "0.15.0"
tracing = "0.1.29"
env_logger = "0.9.0"
openssl = "0.10.38"
actix-rt = "2.5.0"
awc = "3.0.0-beta.14"
futures = "0.3.19"
bundlr-sdk =  { git = "https://github.com/Bundlr-Network/rust-sdk.git" }
num-traits = "0.2.14"
avro-rs = "0.13.0"
async-stream = "0.3.2"
diesel = { version = "1.4.8", features = [ "postgres", "r2d2" ] }
bigint = "4.4.3"
lazy_static = "1.4.0"
bb8 = "0.7.1"
reool = "0.30.0"
jsonwebkey = "0.3.4"
dashmap = "5.0.0"
